ROLE_ADMIN = "Admin"
ROLE_MOD = "Mods"

COLOR_EMBED = 0xED4245

COG_PARTY_MANAGER = "PartyManager"
COG_MATCHMAKING_MANAGER_V2 = "MatchmakingManagerV2"

JOIN_MATCH_2V2_TIMEOUT_SEC = 3 * 60
CHECK_QUEUES_TO_SPAWN_NEW_MATCH_TASK_SEC = 1
CHECK_ACTIVE_MATCHES_FINISHED_TASK_SEC = 5
