SECRETS_JSON = "secrets.json"
SECRET_UBI_AUTHS = "UBI_AUTHS"
SECRET_DISCORD_BOT_TOKEN = "DISCORD_BOT_TOKEN"
SECRET_PASTEBIN_API_DEV_KEY = "PASTEBIN_API_DEV_KEY"
SECRET_PASTES_IO_LOGIN = "PASTES_IO_LOGIN"
SECRET_PASTES_IO_PASSWORD = "PASTES_IO_PASSWORD"

CONFIGS_JSON = "configs.json"
CONFIGS_GLOBAL_LEADERBOARD_ID = "GLOBAL_LEADERBOARD_ID"
CONFIGS_BOT_MESSAGES_CHANNEL_ID = "BOT_MESSAGES_CHANNEL_ID"
CONFIGS_PINGS_ROLE_ID = "PINGS_ROLE_ID"
CONFIGS_PARTY_CHANNEL_ID = "PARTY_CHANNEL_ID"

KEY_TM_ACCOUNT_ID = "tm_account_id"
KEY_DISCORD_ACCOUNT_ID = "discord_account_id"
KEY_ELO = "elo"
KEY_MATCHES_PLAYED = "matches_played"

KEY_QUEUE_ID = "queue_id"
KEY_CAMPAIGN_CLUB_ID = "campaign_club_id"
KEY_CAMPAIGN_ID = "campaign_id"
KEY_MATCH_CLUB_ID = "match_club_id"
KEY_QUEUE_TYPE = "type"
KEY_ACTIVE = "active"
KEY_CHANNEL_ID = "channel_id"
KEY_LEADERBOARD_IDS = "leaderboard_ids"
KEY_CATEGORY_ID = "category_id"

KEY_BOT_MATCH_ID = "bot_match_id"
KEY_TM_MATCH_ID = "tm_match_id"
KEY_TM_MATCH_LIVE_ID = "tm_match_live_id"
KEY_TIME_PLAYED = "time_played"
KEY_RESULTS = "results"

KEY_LEADERBOARD_ID = "leaderboard_id"

KEY_RANK_ROLE_ID = "rank_role_id"
KEY_DISPLAY_NAME = "display_name"
KEY_MIN_ELO = "min_elo"

KEY_RANK_ID = "rank_id"

KEY_CURRENT_VALUE = "current_value"

KEY_PRIMARY_LEADERBOARD_ID = "primary_leaderboard_id"
KEY_PING_ROLE_ID = "ping_role_id"

KEY_EVENT_ID = "event_id"

KEY_MATCHES_WON = "matches_won"

INDEX_DISCORD_ACCOUNT_ID = "discord_account_id"
