QUEUE_MANAGER_CHECK_QUEUES_INTERVAL_SEC = 5
QUEUE_MANAGER_CHECK_MATCH_RESULTS_INTERVAL_SEC = 30
QUEUE_MANAGER_CHECK_KICK_QUEUED_PLAYERS_INTERVAL_SEC = 30
QUEUE_MANAGER_MAX_TIME_IN_QUEUE_SEC = 30 * 60
QUEUE_MANAGER_MIN_TIME_PING_FIRST_PLAYER_JOIN_QUEUE_SEC = 60 * 60

TEAM_BLUE = "Blue"
TEAM_RED = "Red"
