import { Stack, StackProps } from 'aws-cdk-lib';
import { AttributeType, BillingMode, Table } from 'aws-cdk-lib/aws-dynamodb';
import { Bucket, BucketAccessControl, BucketEncryption } from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

export interface StorageStackProps extends StackProps {
    /** The stage of this stack (dev, prod). */
    stage: string,

    /** The account ID this stack will be deployed to. */
    account: string,
}

/**
 * A stack for tables and buckets accessed by the bot.  
 */
export class StorageStack extends Stack {
    public readonly secretsBucket: Bucket;
    public readonly playerProfilesTable: Table;
    public readonly playerElosTable: Table;
    public readonly matchResultsTable: Table;
    public readonly matchQueuesTable: Table;
    public readonly leaderboardsTable: Table;
    public readonly ranksTable: Table;
    public readonly leaderboardRanksTable: Table;
    public readonly nextBotMatchIdTable: Table;
    public readonly persistedMatchesTable: Table;

    constructor(scope: Construct, id: string, props: StorageStackProps) {
        super(scope, id, props);

        /**
         * PlayerProfiles Table
         * 
         * A table for storing player profiles consisting of:
         * - `tm_account_id`: Player's Trackmania account ID (Primary Key)
         * - `discord_account_id`: Player's linked discord account ID (GSI)
         * - `matches_played`: Player's cached number of matches played, negates checking results table (Number)
         */
        this.playerProfilesTable = new Table(this, "PlayerProfilesTable", {
            partitionKey: { name: "tm_account_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-player-profiles-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.playerProfilesTable.addGlobalSecondaryIndex({
            indexName: "discord_account_id",
            partitionKey: { name: "discord_account_id", type: AttributeType.NUMBER },
        });

        /**
         * PlayerElos Table
         * 
         * A table for storing players' ELO for a given Leaderboard ID.
         * - `tm_account_id`: Player's Trackmania account ID (Primary Key)
         * - `leaderboard_id`: Leaderboard ID (Sort Key) (GSI)
         * - `elo`: Player's ELO for a given leaderboard. 
         */
        this.playerElosTable = new Table(this, "PlayerElosTable", {
            partitionKey: { name: "tm_account_id", type: AttributeType.STRING },
            sortKey: { name: "leaderboard_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-player-elos-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.playerElosTable.addGlobalSecondaryIndex({
            indexName: "leaderboard_id",
            partitionKey: { name: "leaderboard_id", type: AttributeType.STRING },
            sortKey: { name: "elo", type: AttributeType.NUMBER },
        });

        /**
         * MatchResults Table
         * 
         * A table for storing match results consisting of:
         * - `bot_match_id`: Match ID created by the bot (Primary Key)
         * - `queue_id`: Queue ID
         * - `tm_match_id`: Match ID generated by trackmania.com (GSI)
         * - `tm_match_live_id`: Match LiveID generated by trackmania.com (GSI)
         * - `time_played`: The time when the match was played (ISO8601 Datetime)
         * - `results`: The results of the match as a json string
         */
        this.matchResultsTable = new Table(this, "MatchResults1v1v1v1Table", {
            partitionKey: { name: "bot_match_id", type: AttributeType.NUMBER },
            tableName: `tm-mm-bot-match-results-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.matchResultsTable.addGlobalSecondaryIndex({
            indexName: "tm_match_id",
            partitionKey: { name: "tm_match_id", type: AttributeType.NUMBER },
        });
        this.matchResultsTable.addGlobalSecondaryIndex({
            indexName: "tm_match_live_id",
            partitionKey: { name: "tm_match_live_id", type: AttributeType.STRING },
        });

        /**
         * MatchQueues Table
         * 
         * A table for storing different match queues consisting of:
         * - `queue_id`: Queue ID (Primary Key)
         * - `display_name`: The displayed name of the queue by the bot
         * - `campaign_club_id`: Club ID containing campaign to use
         * - `campaign_id`: Campaign ID to use for maps
         * - `match_club_id`: Club ID in which the match is hosted
         * - `type`: Type of match queue (1v1v1v1, 2v2, etc)
         * - `active`: Boolean to enable/disable the queue
         * - `channel_id`: Channel ID to host queue view in Discord
         * - `leaderboard_ids`: List of leadboard IDs for which elo is distributed to players. 
         * - `primary_leaderboard_id`: The primary leaderboard ID for which a player's rank is determined to display for the queue.
         * - `ping_role_id`: The ping role for queue notifications directed at general queue audience. 
         * - `category_id`: The discord category ID under which active match channels will be created for players.
         */
        this.matchQueuesTable = new Table(this, "MatchQueuesTable", {
            partitionKey: { name: "queue_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-match-queues-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Leaderboards Table
         * 
         * A table for storing different leaderboards consisting of:
         * - `leaderboard_id`: Leaderboard ID (Primary Key)
         * - `display_name`: The displayed name of the leaderboard by the bot
         * - `channel_id`: Channel ID to host leaderboard view in Discord
         */
        this.leaderboardsTable = new Table(this, "LeaderboardsTable", {
            partitionKey: { name: "leaderboard_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-leaderboards-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Ranks Table
         * 
         * A table for storing the elo cutoffs for each rank with respect to the "global" leaderboard consisting of:
         * - `rank_role_id`: Rank ID as discord role (Primary Key)
         * - `display_name`: Display name of the role
         * - `min_elo`: The minimum elo to get this role 
         */
        this.ranksTable = new Table(this, "RanksTable", {
            partitionKey: { name: "rank_role_id", type: AttributeType.NUMBER },
            tableName: `tm-mm-bot-ranks-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * LeaderboardRanks Table
         * 
         * A table for storing the elo cutoffs for each rank with respect to individual leaderboards consisting of:
         * - `rank_id`: Rank ID (Primary Key)
         * - `leaderboard_id`: Leaderboard ID associated with this rank (GSI)
         * - `display_name`: Display name of the role in profile, leaderboard, etc
         * - `min_elo`: The minimum elo to have this rank 
         */
        this.leaderboardRanksTable = new Table(this, "LeaderboardRanksTable", {
            partitionKey: { name: "rank_id", type: AttributeType.STRING },
            sortKey: { name: "leaderboard_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-leaderboard-ranks-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.leaderboardRanksTable.addGlobalSecondaryIndex({
            indexName: "leaderboard_id",
            partitionKey: { name: "leaderboard_id", type: AttributeType.STRING },
            sortKey: { name: "min_elo", type: AttributeType.NUMBER },
        });

        /**
         * NextBotMatchId Table
         * 
         * A table for storing the next bot match ID consisting of:
         * - `bot_match_id`: Required primary key to access it (Primary Key, String)
         * - `current_value`: The current value of the next bot match ID (Number)
         */ 
        this.nextBotMatchIdTable = new Table(this, "NextBotMatchIdTable", {
            partitionKey: { name: "bot_match_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-next-bot-match-id-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * PersistedMatches Table
         * 
         * A table for storing the actively tracked matches by BMM.
         * The main purpose is to persist matches between service restarts so results can be reported properly.
         * Consists of:
         * - `bot_match_id`: Match ID created by the bot (Primary Key)
         * - `event_id`: The event ID assigned by Nadeo
         * - `queeu_id`: The queue ID for which the match was created
         */
        this.persistedMatchesTable = new Table(this, "PersistedMatchesTable", {
            partitionKey: { name: "bot_match_id", type: AttributeType.NUMBER },
            tableName: `tm-mm-bot-persisted-matches-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Secrets Bucket
         * 
         * A bucket to store encrypted data consisting of a file `secrets.json` of the form:
         * ```
         * { 
         *      "UBI_AUTHS": ["Basic <base64(user:pass)>", ...],
         *      "DISCORD_BOT_TOKEN": "bot_token"
         * }
         * ```
         * 
         * Also stores an updatable `configs.json`. Will create it if doesn't exist. 
         */
        this.secretsBucket = new Bucket(this, "MMBotSecretsBucket", {
            encryption: BucketEncryption.S3_MANAGED,
            accessControl: BucketAccessControl.BUCKET_OWNER_FULL_CONTROL,
            bucketName: `tm-mm-bot-secrets-${props.stage}-${props.account}`
        })
    }
}