import { Stack, StackProps } from 'aws-cdk-lib';
import { AttributeType, BillingMode, Table } from 'aws-cdk-lib/aws-dynamodb';
import { Bucket, BucketAccessControl, BucketEncryption } from 'aws-cdk-lib/aws-s3';
import { Construct } from 'constructs';

export interface StorageStackProps extends StackProps {
    /** The stage of this stack (dev, prod). */
    stage: string,

    /** The account ID this stack will be deployed to. */
    account: string,
}

/**
 * A stack for tables and buckets accessed by the bot.  
 */
export class StorageStack extends Stack {
    public readonly secretsBucket: Bucket;
    public readonly playerProfilesTable: Table;
    public readonly playerElosTable: Table;
    public readonly matchResultsTable: Table;
    public readonly matchQueuesTable: Table;
    public readonly leaderboardsTable: Table;
    public readonly ranksTable: Table;

    constructor(scope: Construct, id: string, props: StorageStackProps) {
        super(scope, id, props);

        /**
         * PlayerProfiles Table
         * 
         * A table for storing player profiles consisting of:
         * - `tm_account_id`: Player's Trackmania account ID (Primary Key)
         * - `discord_account_id`: Player's linked discord account ID (GSI)
         * - `matches_played`: Player's cached number of matches played, negates checking results table (Number)
         */
        this.playerProfilesTable = new Table(this, "PlayerProfilesTable", {
            partitionKey: { name: "tm_account_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-player-profiles-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.playerProfilesTable.addGlobalSecondaryIndex({
            indexName: "discord_account_id",
            partitionKey: { name: "discord_account_id", type: AttributeType.NUMBER },
        });

        /**
         * PlayerElos Table
         * 
         * A table for storing players' ELO for a given Leaderboard ID.
         * - `tm_account_id`: Player's Trackmania account ID (Primary Key)
         * - `leaderboard_id`: Leaderboard ID (Sort Key) (GSI)
         * - `elo`: Player's ELO for a given leaderboard. 
         */
        this.playerElosTable = new Table(this, "PlayerElosTable", {
            partitionKey: { name: "tm_account_id", type: AttributeType.STRING },
            sortKey: { name: "leaderboard_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-player-elos-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.playerElosTable.addGlobalSecondaryIndex({
            indexName: "leaderboard_id",
            partitionKey: { name: "leaderboard_id", type: AttributeType.STRING },
            sortKey: { name: "elo", type: AttributeType.NUMBER },
        });

        /**
         * MatchResults Table
         * 
         * A table for storing match results consisting of:
         * - `bot_match_id`: Match ID created by the bot (Primary Key) <-- for now this is just tm_match_id
         * - `queue_id`: Queue ID
         * - `tm_match_id`: Match ID generated by trackmania.com (GSI)
         * - `tm_match_live_id`: Match LiveID generated by trackmania.com (GSI)
         * - `time_played`: The time when the match was played (ISO8601 Datetime)
         * - `results`: The results of the match as a json string
         */
        this.matchResultsTable = new Table(this, "MatchResults1v1v1v1Table", {
            partitionKey: { name: "bot_match_id", type: AttributeType.NUMBER },
            tableName: `tm-mm-bot-match-results-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });
        this.matchResultsTable.addGlobalSecondaryIndex({
            indexName: "tm_match_id",
            partitionKey: { name: "tm_match_id", type: AttributeType.NUMBER },
        });
        this.matchResultsTable.addGlobalSecondaryIndex({
            indexName: "tm_match_live_id",
            partitionKey: { name: "tm_match_live_id", type: AttributeType.STRING },
        });

        /**
         * MatchQueues Table
         * 
         * A table for storing different match queues consisting of:
         * - `queue_id`: Queue ID (Primary Key)
         * - `campaign_club_id`: Club ID containing campaign to use
         * - `campaign_id`: Campaign ID to use for maps
         * - `match_club_id`: Club ID in which the match is hosted
         * - `type`: Type of match queue (1v1v1v1, 2v2, etc)
         * - `active`: Boolean to enable/disable the queue
         * - `channel_id`: Channel ID to host queue view in Discord
         * - `leaderboard_ids`: List of leadboard IDs for which elo is distributed to players. 
         */
        this.matchQueuesTable = new Table(this, "MatchQueuesTable", {
            partitionKey: { name: "queue_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-match-queues-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Leaderboards Table
         * 
         * A table for storing different leaderboards consisting of:
         * - `leaderboard_id`: Leaderboard ID (Primary Key)
         * - `channel_id`: Channel ID to host leaderboard view in Discord
         */
        this.leaderboardsTable = new Table(this, "LeaderboardsTable", {
            partitionKey: { name: "leaderboard_id", type: AttributeType.STRING },
            tableName: `tm-mm-bot-leaderboards-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Ranks Table
         * 
         * A table for storing the elo cutoffs for each rank with respect to the "global" leaderboard consisting of:
         * - `rank_role_id`: Rank ID as discord role (Primary Key)
         * - `display_name`: Display name of the role
         * - `min_elo`: The minimum elo to get this role 
         */
        this.ranksTable = new Table(this, "RanksTable", {
            partitionKey: { name: "rank_role_id", type: AttributeType.NUMBER },
            tableName: `tm-mm-bot-ranks-${props.stage}-${props.account}`,
            billingMode: BillingMode.PAY_PER_REQUEST,
        });

        /**
         * Secrets Bucket
         * 
         * A bucket to store encrypted data consisting of a file `secrets.json` of the form:
         * ```
         * { 
         *      "UBI_AUTHS": ["Basic <base64(user:pass)>", ...],
         *      "DISCORD_BOT_TOKEN": "bot_token"
         * }
         * ```
         * 
         * Also stores an updatable `configs.json`. Will create it if doesn't exist. 
         */
        this.secretsBucket = new Bucket(this, "MMBotSecretsBucket", {
            encryption: BucketEncryption.S3_MANAGED,
            accessControl: BucketAccessControl.BUCKET_OWNER_FULL_CONTROL,
            bucketName: `tm-mm-bot-secrets-${props.stage}-${props.account}`
        })
    }
}