name: Pull Request Checks

on:
  pull_request:  
    branches:
      - master  

jobs:
  pre-commit:
    name: Run Pre-Commit Hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"  # Change this to match your project

      - name: Install Pre-Commit
        run: pip install pre-commit

      - name: Run Pre-Commit Hooks
        run: |
          pre-commit install --config lib/mm-bot/.pre-commit-config.yaml
          pre-commit run --config lib/mm-bot/.pre-commit-config.yaml --all-files

  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: pre-commit

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run Pytest
        run: |
          cd lib/mm-bot/
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest
          pytest --maxfail=1 --disable-warnings 